name: dating_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  awesome_notifications: ^0.8.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.12.2
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  firebase_storage: ^11.4.1
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  google_sign_in: ^6.1.5
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  path: ^1.8.3
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  provider: ^6.0.5
  sticky_grouped_list: ^3.1.0
  transparent_image: ^2.0.1
  video_player: ^2.8.1
  video_trimmer: ^3.0.1
  fluttertoast: ^8.2.2
  sign_button: ^2.0.6
  carousel_slider: ^4.2.1
  path_provider: ^2.1.0
  story: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
