// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTPPQ10GgLW2AeNTQ8GsQqOnlGzhbsFiU',
    appId: '1:365809358893:web:78fd46b6daa37c73a080a4',
    messagingSenderId: '365809358893',
    projectId: 'datingapp-84823',
    authDomain: 'datingapp-84823.firebaseapp.com',
    storageBucket: 'datingapp-84823.appspot.com',
    measurementId: 'G-5KDBWCK913',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe_pcX5-L0qPTp-dt65Md_ChAid08OPiI',
    appId: '1:365809358893:android:cf3b395321ce390ba080a4',
    messagingSenderId: '365809358893',
    projectId: 'datingapp-84823',
    storageBucket: 'datingapp-84823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPK-w33vuMnzLCFM9jFb7LSMNA2NtfR7w',
    appId: '1:365809358893:ios:383573954f09bdbaa080a4',
    messagingSenderId: '365809358893',
    projectId: 'datingapp-84823',
    storageBucket: 'datingapp-84823.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPK-w33vuMnzLCFM9jFb7LSMNA2NtfR7w',
    appId: '1:365809358893:ios:ca55461fb939c926a080a4',
    messagingSenderId: '365809358893',
    projectId: 'datingapp-84823',
    storageBucket: 'datingapp-84823.appspot.com',
    iosBundleId: 'com.example.datingApp.RunnerTests',
  );
}
